list_of_mqtt_topics = [("/devices/wb-gpio/controls/A1_OUT", 0),
                    ("/devices/wb-gpio/controls/A2_OUT", 0),
                    ("/devices/wb-gpio/controls/A3_OUT", 0),
                    ("/devices/wb-gpio/controls/D1_OUT", 0),
                    ("/devices/CoolingSystem/controls/Auto Mode", 0),
                    ("/devices/CoolingSystem/controls/Down limit", 0),
                    ("/devices/CoolingSystem/controls/Up limit", 0),
                    ("/devices/CoolingSystem/controls/Wait time", 0),
                    ("/devices/CoolingSystem/controls/Counter", 0),
                    ("/devices/CoolingSystem/controls/Current state", 0),
                    ("/devices/CoolingSystem/controls/DT1 Value", 0),
                    ("/devices/CoolingSystem/controls/DT6 Value", 0),
                    ("/devices/CoolingSystem/controls/DT8 Value", 0),
                    ("/devices/CoolingSystem/controls/DT9 Value", 0),
                    ("/devices/CoolingSystem/controls/DT10 Value", 0),
                    ]